### ISSUE TITLE
interp_restarts cannot compile in dev/MAPL-2.0

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_GridComp#68]
Per @kgerheiser:

There is only one other place in the code that uses this routine; interp_restarts.F90 uses it in FVDyCoreCubed/. And I think having `lm` is the right decision because `lm_world` exists in the structure but isn't filled by this subroutine while `im` and `jm` are.

_Originally posted by @kgerheiser in https://github.com/GEOS-ESM/MAPL/pull/33#issuecomment-526405370_

**Comment by mathomp4** [comment]
And, when I try to build:
```
[ 97%] Building Fortran object src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/FVdycoreCubed_GridComp/CMakeFiles/interp_restarts.x.dir/interp_restarts.F90.o
/discover/swdev/mathomp4/Models/GEOSgcm-from-Github-MAPL20/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/FVdycoreCubed_GridComp/interp_restarts.F90(440): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [JE]
   call ArrDescrInit(Arrdes,MPI_COMM_WORLD,npx-1,(npx-1)*6,npes_x,npes_y*6,n_readers,n_writers,isl,iel,jsl,jel,rc=status)
--------^
```

**Comment by mathomp4** [comment]
I think the issue is that `interp_restarts` needs an `npz` added? Or should it be `npz+1`? The FV3 code confuses me sometimes. That's why I bother poor @bena-nasa

**Comment by kgerheiser** [comment]
@mathomp4 

That is correct. I just gave it `npz`, though I wasn't aware of any `npz+1` kind of confusion

**Comment by bena-nasa** [comment]
This should be fixed now. Approved Kyle's pull request

**Comment by mathomp4** [comment]
> @mathomp4
> 
> That is correct. I just gave it `npz`, though I wasn't aware of any `npz+1` kind of confusion

Well I'm never sure what's the correct "number of levels" in some routines. I figured you or @bena-nasa would know.
